name: altur_nearby_stops
description: "An app to find nearby stops for the Altur study case."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8
  
  # !!! In real projects these packages are not needed, they are used for better use case design. !!!
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.5

  # Localization
  easy_localization: ^3.0.7+1

  # Navigation
  go_router: ^15.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

