name: altur_nearby_stops
description: "An app to find nearby stops for the Altur study case."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

